[workspace]
members = [
  # CHILDSTREAMER
  "child-streamer/child-streamer",
  "child-streamer/child-streamer-crate",
  "child-streamer/child-streamer-proxy",
  "child-streamer/child-streamer-tests",
]