[workspace]
members = [
  # MINTER
  "minter/minter",
  "minter/minter-crate",
  "minter/minter-proxy",
  "minter/minter-tests",
  # GAUGE CONTROLLER
  "gauge-controller/gauge-controller",
  "gauge-controller/gauge-controller-crate",
  "gauge-controller/gauge-controller-proxy",
  "gauge-controller/gauge-controller-tests",
  # REWARD ONLY GAUGE
  "reward-only-gauge/reward-only-gauge",
  "reward-only-gauge/reward-only-gauge-crate",
  "reward-only-gauge/reward-only-gauge-proxy",
  "reward-only-gauge/reward-only-gauge-tests",
  # VESTING ESCROW
  "vesting-escrow/vesting-escrow",
  "vesting-escrow/vesting-escrow-crate",
  "vesting-escrow/vesting-escrow-proxy",
  "vesting-escrow/vesting-escrow-tests",
  # VESTING ESCROW FACTORY
  "vesting-escrow-factory/vesting-escrow-factory",
  "vesting-escrow-factory/vesting-escrow-factory-crate",
  "vesting-escrow-factory/vesting-escrow-factory-proxy",
  "vesting-escrow-factory/vesting-escrow-factory-tests",
  # COMMON
  "common",
  # SESSION CODE
  "session-code",
  # ERC20
  "erc20/erc20",
  "erc20/erc20-crate",
  "erc20/erc20-proxy",
  "erc20/erc20-tests",
  # VotingEscrow
  "voting-escrow/voting-escrow",
  "voting-escrow/voting-escrow-crate",
  "voting-escrow/voting-escrow-tests",
  # Fee Distributor 
  "fee-distributor/fee-distributor",
  "fee-distributor/fee-distributor-crate",
  "fee-distributor/fee-distributor-tests",
  # Liquidity Gauge Reward
  "liquidity-gauge-reward/liquidity-gauge-reward",
  "liquidity-gauge-reward/liquidity-gauge-reward-crate",
  "liquidity-gauge-reward/liquidity-gauge-reward-tests",

  "erc20-crv/erc20_crv",
  "erc20-crv/erc20_crv_tests",
  "erc20-crv/session_code",
  
  "vesting-escrow-simple/vesting-escrow-simple",
  "vesting-escrow-simple/vesting-escrow-simple-tests",
  # ERC20
  "erc20/erc20",
  "erc20/erc20-crate",
  "erc20/erc20-proxy",
  "erc20/erc20-tests",
  # Liquidity Gauge Reward Wrapper
  "liquidity-gauge-reward-wrapper/liquidity-gauge-reward-wrapper",
  "liquidity-gauge-reward-wrapper/liquidity-gauge-reward-wrapper-crate",
  "liquidity-gauge-reward-wrapper/liquidity-gauge-reward-wrapper-tests",
  # SESSION CODE
  "liquidity-gauge-reward-wrapper/liquidity-gauge-reward-wrapper-session-code",

  "curve-token-v1/curve-token-v1",
  "curve-token-v1/curve-token-v1-tests",
  "curve-token-v2/curve-token-v2",
  "curve-token-v2/curve-token-v2-tests",
  "curve-token-v3/curve-token-v3",
  "curve-token-v3/curve-token-v3-tests"
]

[profile.release]
codegen-units = 1
lto = true
