[package]
name = "reward-only-gauge-tests"
version = "0.2.1"
authors = ["Muhammad Adrees <muhammad.adrees@scytalelabs.com>"]
edition = "2018"

[dependencies]
casper-contract = "1.4.4"
casper-types = "1.5.0"
casper-engine-test-support = "2.1.0"
casper_types_derive = "0.1.0"
common = { path = "../../common" }
contract-utils = { path = "../../utils/contract-utils" }
test-env = { path = "../../utils/test-env" }
blake2 = "0.9.1"
hex = "0.4.3"

[features]
default = ["casper-contract/std", "casper-types/std", "casper-contract/test-support"]