
[package]
name = "contract-utils"
version = "0.1.0"
authors = ["Nouman Nadeem <nouman.nadeem.zafar@scytalelabs.com>"]
edition = "2018"

[dependencies]
casper-contract = "1.4.3"
casper-types = "1.4.4"
hex = { version = "0.4.3", default-features = false }