[package]
name = "liquidity-gauge"
version = "0.2.0"
authors = ["Bassam Monib <bassam.munib@scytalelabs.com>"]
edition = "2018"

[dependencies]
casper-contract = "=1.4.3"
casper-types = "=1.4.6"
contract-utils = { path = "../../../utils/contract-utils" }
liquidity-gauge-crate = { path = "../liquidity-gauge-crate" }

[[bin]]
name = "liquidity-gauge"
path = "bin/liquidity_gauge.rs"
bench = false
doctest = false
test = false

[features]
default = ["casper-contract/std", "casper-types/std"]