[package]
name = "reward-only-gauge"
version = "0.2.0"
authors = ["Muhammad Adrees <muhammad.adrees@scytalelabs.com>"]
edition = "2018"

[dependencies]
casper-contract = "1.4.4"
casper-types = "1.5.0"
reward-only-gauge-crate = { path = "../reward-only-gauge-crate" }
curve-erc20-crate = {path="../../curve-erc20/curve-erc20-crate"}
curve-casper-erc20-crate = { path = "../../curve-casper-erc20-crate" }
casperlabs-contract-utils = "0.2.1"

[[bin]]
name = "reward-only-gauge-token"
path = "bin/reward_only_gauge_token.rs"
bench = false
doctest = false
test = false

[features]
default = ["casper-contract/std", "casper-types/std"]