[package]
name = "voting-escrow"
version = "0.2.0"
authors = ["Bassam Monib <bassam.munib@scytalelabs.com>"]
edition = "2018"

[dependencies]
casper-contract = "1.4.4"
casper-types = "1.5.0"
casperlabs-contract-utils = "0.1.0"
voting-escrow-crate = { path = "../voting-escrow-crate" }

[[bin]]
name = "voting-escrow"
path = "bin/voting_escrow.rs"
bench = false
doctest = false
test = false

[features]
default = ["casper-contract/std", "casper-types/std"]