[package]
name = "liquidity-gauge-v3-tests"
version = "0.2.1"
authors = ["Nouman Nadeem <nouman.nadeem.zafar@scytalelabs.com>"]
edition = "2018"

[dependencies]
casper-contract = "1.4.4"
casper-types = "1.5.0"
casper-engine-test-support = "2.1.0"
casperlabs-contract-utils = "0.2.1"
curve-erc20-crate = {path="../../curve-erc20/curve-erc20-crate"}
casperlabs-test-env = "0.3.0"
casper_types_derive = "0.1.0"
blake2 = "0.9.1"
hex = "0.4.3"
base64 = "0.13.0"
common = { path = "../../common" }

[features]
default = ["casper-contract/std", "casper-types/std", "casper-contract/test-support"]