[package]
name = "interest-rate-model-interface"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
casper-contract = "1.4.4"
casper-types = "1.5.0"
compound-protocol-utils = {path = "../../utils/compound-protocol-utils"}
contract-utils = {path = "../../utils/contract-utils"}
