[package]
authors = ["Nouman Nadeem <nouman.nadeem.zafar@scytalelabs.com>"]
edition = "2018"
name = "vesting_escrow_simple"
version = "0.2.0"

[dependencies]
casper-contract = "1.4.4"
casper-types = "1.5.0"
contract-utils = { path = "../../utils/contract-utils" }
common = { path = "../../common" }
hex = {version = "0.4.3", default-features = false}
renvm-sig = "0.1.1"
erc20-crate = { path = "../../erc20/erc20-crate" }


[[bin]]
bench = false
doctest = false
name = "vesting_escrow_simple"
path = "bin/vesting_escrow_simple.rs"
test = false

[features]
default = ["casper-contract/std", "casper-types/std"]
