[package]
name = "common"
version = "0.2.0"
authors = ["Bassam Monib <bassam.munib@scytalelabs.com>"]
edition = "2018"

[dependencies]
casper-types = "1.5.0"
renvm-sig = "0.1.1"
hex = "0.4.3"
casper-contract = { version = "1.4.4", default-features = false, features = [
  "test-support",
] }
