[package]
name = "erc20-crv-session-code"
version = "0.2.0"
edition = "2018"

[dependencies]
casper-contract = "1.4.4"
casper-types = "1.5.0"
common = { path = "../../common" }
crv20 = "0.1.0"

[[bin]]
name = "erc20-crv-session-code"
path = "bin/main.rs"
bench = false
doctest = false
test = false