[package]
name = "liquidity-gauge-wrapper"
version = "0.2.0"
authors = ["Saad Majeed <saad.majeed@scytalelabs.com>"]
edition = "2018"

[dependencies]
casper-contract = "1.4.4"
casper-types = "1.5.0"
casperlabs-contract-utils = "0.1.0"
liquidity-gauge-wrapper-crate = { path = "../liquidity-gauge-wrapper-crate" }

[[bin]]
name = "liquidity-gauge-wrapper"
path = "bin/liquidity_gauge_wrapper.rs"
bench = false
doctest = false
test = false

[features]
default = ["casper-contract/std", "casper-types/std"]