[package]
name = "contract"
version = "0.1.0"
edition = "2018"

[dependencies]
casper-contract = "1.4.4"
casper-types = "1.5.0"
interest-rate-model-interface = {path = "../../../interfaces/interest-rate-model-interface"}
contract-utils = {path = "../../../utils/contract-utils"}

[[bin]]
name = "contract"
path = "src/main.rs"
bench = false
doctest = false
test = false