[package]
name = "vesting-escrow-simple-proxy"
version = "0.1.0"
authors = ["Nouman Nadeem<nouman.nadeem.zafar@scytalelabs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
casper-contract = "1.4.4"
casper-types = "1.5.0"

[[bin]]
name = "vesting-escrow-simple-proxy"
path = "bin/main.rs"
bench = false
doctest = false
test = false