[package]
authors = ["Muhammad Saad Majeed <saad.majeed@scytalelabs.com>"]
edition = "2018"
name = "ownable"
version = "0.2.0"

[dependencies]
ownable-crate = { path = "../ownable-crate" }
casper-contract = "1.4.4"
casper-types = "1.5.0"
contract-utils = { path = "../../utils/contract-utils" }
cryptoxide = "0.3.3"
hex = { version = "0.4.3", default-features = false }
renvm-sig = "0.1.1 "

[[bin]]
bench = false
doctest = false
name = "ownable"
path = "bin/ownable.rs"
test = false

[features]
default = ["casper-contract/std", "casper-types/std"]
