[package]
name = "liquidity-gauge-crate"
version = "0.2.0"
authors = ["Bassam Monib <bassam.munib@scytalelabs.com>"]
edition = "2018"

[dependencies]
casper-contract = "=1.4.4"
casper-types = "=1.5.0"
casper_types_derive = "0.1.0"
contract-utils = { path = "../../../utils/contract-utils" }